import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AlertProvider } from "./Context/AlertContext";
import Alert from "./ui/alert/alert";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <AlertProvider>
          <Alert />
          {children}
        </AlertProvider>
      </body>
    </html>
  );
}
